version: '3.1'
services:
  app:
    container_name: app-book-viewer
    image: app-book-viewer
    build: ./
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: mladen
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mladen
      POSTGRES_DB: postgres